services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: pnpm run start:dev
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  docker-nest-postgres:
